### ISSUE TITLE
Alpha testing

### ISSUE THREAD

**Issue by cmllr** [gethitchhike/hitchhike#1]
![alt tag](https://avatars0.githubusercontent.com/u/13689977?v=3&s=200)
After about **300** commits and **three** milestones, Hitchhike will be soon ready for alpha testing. You will be able to power your blog with Hitchhike.

Please note: Not all units are present, e. g. you will have no backend!

**Privacy note:** The `alphatest` module will create a hash from your Webserver Software (`$_SERVER["SERVER_SOFTWARE"]`) and your hostname (via `gethostname()`). The hash will be submitted to `io.0fury.de`. This information will be deleted after the end of the alpha test.
## What do I need for testing?
- PHP 5.6 or later
- composer 
- nerves of steel
## Things you are allowed to do
- Testing
- Give feedback
## Things you are **not** allowed to
- Fork the alpha version 
- Use in production
- Continue usage after alpha test
- Delete or disable the `alphatest` module
## Wait, the gethitchhike/hitchhike repository is still empty?

This is a closed alpha. Comment on this issue to qualify yourself for the closed alpha. The first alpha is limited by 10 users. Please leave a public email so I can contact you.
## Why the closed, "secret" test? Why the user limit?

On my last large project, I released the software too early, the software was unstable and needed a lot of time to get stable. This time, I want to avoid this problem with closed-first test. Also, I don't know if I will release the final product with an FLOSS or proprietary license.

**Comment by moqmar** [comment]
I'd like to try that out! Not sure about the "nerves of steel" qualification though... :D (hitchhike-beta@mo-mar.de)

**Comment by cmllr** [comment]
@moqmar the version may be unstable, that is the point ^^

**Comment by moqmar** [comment]
Sure, that's what I expect from an alpha version :smile:

Edit: there are reactions for issues now? o.O

**Comment by cmllr** [comment]
Jap, they where added a few days ago.

**Comment by toXel** [comment]
I'd like to alpha test this thing! Waited a long time for it ;P

**Comment by markhaehnel** [comment]
Note down my name on your list.

**Comment by menzerath** [comment]
I'm still in!

**Comment by rflrkn** [comment]
Same! I'm also in. And I think you've got enough contact data for communication :D

**Comment by elomatreb** [comment]
If it's flatfile based, I'd like to try it too. Email is [ole@bertr.am](mailto:ole@bertr.am).

**Comment by vainamov** [comment]
As you might noticed on twitter, I'm in as well ^^.

**Comment by cmllr** [comment]
@vainamov I need an email of you

**Comment by vainamov** [comment]
@squarerootfury vainamo@outlook.de

**Comment by cmllr** [comment]
After some rethinking I decided to ship the backend module with the alpha. This will take some days, sorry. :sob: 

Currently, I have another problem. Maybe some of you can help I wan't to publish the sourcecode here on GitHub, but also I want to prevent usage by everyone of the alpha. Any ideas?

Today, the methods for `hm.php install <unit>` and `hm.php remove <unit>` are missing. I want to include them in the alpha, too. This methods require a infrastructure, which has to be designed first. Without this functions, your possibilities are kind of limited. So I have to implement them first.

**Comment by elomatreb** [comment]
You would need a private repository for that. Github offers a free educational account with five private repositories, but I don't know the exact eligibility requirements.

Alternatively you could install something like [gitlab](https://about.gitlab.com/) on your server.

**Comment by cmllr** [comment]
@elomatreb I'm not eligible for that. Currently, the repository is in a private gogs installation, but the user management would be difficult to create an account for each tester. And I want to have the issues here, not in gogs.

**Comment by elomatreb** [comment]
@squarerootfury Unless you want to pay for Github (25$ / Month for organisations), giving out user accounts on your gogs is probably your best option. I'm sure there are importer tools available to transfer issues from gogs to Github once the testing becomes public.

**Comment by cmllr** [comment]
I think I will provide user credentials for source access to my gogs instance.

**Comment by vainamov** [comment]
Alternatively you could use gitlab.com, as it provides unlimeted free private repositories.

**Comment by cmllr** [comment]
@vainamov I won't set up account in other services. Gogs will fullfill my needs for this. There will be a `anymous` clone account that you can aquire the source code.

**Comment by cmllr** [comment]
There is a place for discussion: https://gitter.im/gethitchhike/hitchhike

**Comment by apertureless** [comment]
༼ つ _ ༽つ gief test

**Comment by cmllr** [comment]
@apertureless https://gitter.im/gethitchhike/hitchhike

**Comment by cmllr** [comment]
Private alpha testing will be soon finished: https://0fury.de/blog/?/post/Announcing+Hitchhike+0.4+%27Almighty+Bob%27/
