### ISSUE TITLE
Name used for comments isn't stored

### ISSUE THREAD

**Issue by moqmar** [gethitchhike/hitchhike#3]
It would be great if the name used for comments was stored in a cookie, so when writing multiple comments you don't always have to type your name again.

**Comment by elomatreb** [comment]
[localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) (or sessionStorage) is probably more suited for things like this, since cookies will needlessly be transmitted with HTTP requests.

**Comment by cmllr** [comment]
The issue was fixed in commit 433fdab3035d85b169aa4e5664b071590b2f4f99

As @elomatreb suggested I used localStorage for the feature.
