### ISSUE TITLE
Codename pattern for future versions

### ISSUE THREAD

**Issue by cmllr** [gethitchhike/hitchhike#8]
Hitchhike will soon reach version `0.4`, the current version is `0.3.x`. This version is the first one with version codenames. 

Make suggestions for version codenames. Please tell the background of your suggestion, too. It is planned that the codename pattern will be kept for the future versions. 

**Examples**
- Redundancy used Cloud Types, e.g "Lenticularis"
- Ubuntu uses Animals starting with the next letter of the alphabet with an attribute, e. g. "Vivid Vervet"
- WordPress uses Jazz Musicans as Codename
- Android uses Candy names

**Comment by menzerath** [comment]
What about using traditional German dishes like _Sauerkraut_ or _Currywurst_? :fork_and_knife:

**Comment by cmllr** [comment]
Another suggestion:

> männliche Vornamen (alphabetisch) für Major Version, weibliche für Minor. Oder umgekehrt: Anja (1.0), Aaron (1.1), Achim (1.2) usw.

@MarvinMenzerath no. Simply no.

**Comment by cmllr** [comment]
Suggestion: https://en.wikipedia.org/wiki/List_of_minor_The_Hitchhiker%27s_Guide_to_the_Galaxy_characters

**Comment by cmllr** [comment]
Another suggestion:

https://en.wikipedia.org/wiki/List_of_people_considered_father_or_mother_of_a_scientific_field

**Comment by markhaehnel** [comment]
This could help: https://namingschemes.com/

**Comment by christianmalek** [comment]
How about irrational numbers?

**Comment by cmllr** [comment]
@Phisherman example?

**Comment by christianmalek** [comment]
Another idea: https://en.wikipedia.org/wiki/Hitchhiking#Notable_hitchhikers
